#!/bin/bash
set -euo pipefail
#$ -N joblog_demux_forward
#$ -t 1-288         
#$ -tc 12           
#$ -cwd
#$ -pe smp 4        
#$ -o job_logs/
#$ -e job_logs/
#$ -q largemem
#$ -M nvincen2@nd.edu
#$ -m n

mkdir -p job_logs/

module load bio/0724

MANIFEST="../demux_out/01a_reverse/summaries/fwd_input_manifest.csv"

# Read sample name for this task
LINE=$(tail -n +2 "$MANIFEST" | sed -n "${SGE_TASK_ID}p")

# Basic sanity check
# if [ -z "${LINE}" ]; then
#   echo "ERROR: No sample found for SGE_TASK_ID=${SGE_TASK_ID} (check fwd_input_manifest.csv)" >&2
#   exit 2
# fi

# Parse fields (comma separated)
SAMPLE=$(echo "$LINE" | cut -f1 -d ',')
REVBIN=$(echo "$LINE" | cut -f2 -d ',')

# --- Redirect stdout/stderr to sample-specific files ---
exec > job_logs/joblog_fwd_${SAMPLE}_${REVBIN}.out
exec 2> job_logs/joblog_fwd_${SAMPLE}_${REVBIN}.err

echo "=== Starting pipeline for ${SAMPLE} ${REVBIN} ==="

# Step 2: Forward demux
bash ./01b_forward_demux.sh ${SAMPLE} ${REVBIN}
