#!/bin/bash
set -euo pipefail
#$ -N clustering_byHeader_id
#$ -pe smp 8
#$ -o job_logs/
#$ -e job_logs/
#$ -q largemem
#$ -M nvincen2@nd.edu
#$ -m abe

conda activate clustering-env

python3.14 /temp180/mpfrende/nvincen2/Metagenomics/random/cluster_by_header.py \
--in_fasta /temp180/mpfrende/nvincen2/Metagenomics/DBs/DB_data/dada_formatted/noEmpty_dada_addSpecies.fasta \
--id_thresh 1.0 \
--out_prefix id_cluster_noempty_newparse \
--threads 8
