#!/bin/bash
#$ -M nvincen2@nd.edu
#$ -m abe
#$ -q largemem
#$ -pe smp 16
#$ -N dada2_mICOint_tax
#$ -o job_logs/
#$ -e job_logs/

conda activate dada2-env

Rscript /temp180/mpfrende/nvincen2/Metagenomics/04_dadaTax/dada_tax_scripts/dada_tax_assign.R \
        --RDS /temp180/mpfrende/nvincen2/Metagenomics/03_dadaASV/dada_asv_output/mICOintF/mICOintF_seqtab.nochim.Rds \
        --refFile /temp180/mpfrende/nvincen2/Metagenomics/DBs/DB_data/dada_formatted/tax_cluster_noempty_newparse.clustered.fasta \
        --spref /temp180/mpfrende/nvincen2/Metagenomics/DBs/DB_data/dada_formatted/id_cluster_noempty_newparse.clustered.fasta \
        --out /temp180/mpfrende/nvincen2/Metagenomics/04_dadaTax/dada_tax_output/mICOintF \
        --outprefix "mICOintF"
        