#!/bin/bash
set -euo pipefail
#$ -N joblog_cat
#$ -cwd
#$ -pe smp 1 
#$ -o job_logs/
#$ -e job_logs/
#$ -q largemem
#$ -M nvincen2@nd.edu
#$ -m abe

module load R

mandir="../demux_out/01b_forward/summaries/total_fwd_out_manifest.csv"
outdir="../demux_out/01c_rescue"

lcodir=${outdir}/LCO1490
micodir=${outdir}/mICOintF
ssudir=${outdir}/SSUF04

mkdir -p $lcodir
mkdir -p $micodir
mkdir -p $ssudir

# Run script that makes rescue_add.sh
Rscript make_cat_script.R $mandir

# Run rescue_add.sh - outputs go to outdir
bash rescue_add.sh $outdir

# Move outputs into their own folders based on forward primer
mv ${outdir}/*LCO* $lcodir
mv ${outdir}/*mICO* $micodir
mv ${outdir}/*SSU* $ssudir