#!/bin/bash
#$ -pe smp 64
#$ -q largemem
#$ -N ampliseq_full
#$ -o job_logs/
#$ -e job_logs/
#$ -M nvincen2@nd.edu
#$ -m abe

# Load the nf-core software module
conda activate nfcore-env
# module load bio/nf-core

# Set the Singularity cache directory
export NXF_SINGULARITY_CACHEDIR=/temp180/mpfrende/nvincen2/.singularity
# export NXF_SINGULARITY_CACHEDIR=/software/n/nf-core/3.3.1/singularity
export NXF_APPTAINER_CACHEDIR=/temp180/mpfrende/nvincen2/.apptainer

# Run the pipeline
nextflow run nf-core/ampliseq \
-profile apptainer \
-r 2.15.0 \
-params-file /temp180/mpfrende/nvincen2/Metagenomics/nf-core_ampliseq/nfcore_scripts/ampliseq-nf-params.yml \
-name run64_less_ancom \
--outdir /temp180/mpfrende/nvincen2/Metagenomics/nf-core_ampliseq/nfcore_output/run2/
